server:
  port: 9001
spring:
  application:
#    name: tc-login
    name: ${sn.login}
  data:
    mongodb:
      database: tc_mongodb
      uri: mongodb://10.0.0.134:27017
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true