server:
  port: 7001
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false # whether register self to eureka server
    fetch-registry: false # whether to get info from eureka
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/